name: bencohen_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - obspy
  - pandas
  - nbgitpuller
  - wget
  - pooch
  - pip=20
  - xarray
  - gdal
  - geopandas
  - jupyterlab